theme: jekyll-theme-minimal
title: Nicolas Lacerda
name: Nicolas Lacerda Website

plugins:
  - jekyll-feed
  - jekyll-seo-tag  

url: https://NicolasLacerdaF.github.io



description: "Site pessoal de Nicolas Lacerda"

# social links
Instagram_username: @nicolaslacerda
github_username:  NicolasLacerdaF

